id: 3a1d6781-4a74-42c2-81e0-221f32041825
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /hello2
domains:
    - somedomain
execution:
    timeout: 10s
    memory: 23MB
    call: triplo
