id: QmQazSMmMztAFkECFpvNjGMJpaYH4CvTTt85GDj1yYgt4a
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /helloworld
domains:
    - GoodDomain
execution:
    timeout: 10s
    memory: 10MB
    call: doStuff
