id: Qmdpmqttpns23a8nqXfLNdJpHRsrMb2xDUQpCo6yqVsPBM
description: ""
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /dlonly
domains:
    - GoodDomain
includes:
    - /functions/dreamland.go
execution:
    timeout: 10s
    memory: 10MB
    call: getsocketurl
