id: QmQazSMmMztAFkECFpvNjGMJpaYH4CvHTt85GDj1yYgt4a
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /getsocketurl
domains:
    - GoodDomain
execution:
    timeout: 10s
    memory: 10MB
    call: getsocketurl
