id: 2463235f-54ad-43bc-b5ad-e466c194de12
description: This Function should work
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /goopath
domains:
    - GoodDomain
libraries:
    - testLibrary
    - testLibrary2
includes:
    - /functions/GoodFunc.go
execution:
    timeout: 10s
    memory: 10MB
    call: ping
