id: QmRf1FqCMVipMmGaCkT3jRLBW2AcE569veE7yCY7Tz8ydX
description: This Function should work
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /path
        - /goopath
        - /bapath
domains:
    - NewDomain
includes:
    - /functions/GoodFunc_clone.go
execution:
    timeout: 10s
    memory: 10MB
    call: ping
