id: QmNw6C5RtfMWJWkj5TTzKD9nJZBHFEGutTKXvj4EjmH3wJ
description: ""
tags: []
trigger:
    type: pub-sub
    channel: ""
    local: false
includes:
    - /functions/GoodFunc_pubsub.go
execution:
    timeout: 10s
    memory: 10MB
    call: ping
