id: QmVbXmf7gYKJZFudqBw189aifYD765NUuQeSkv9VKAb8bV
description: This Function should work
tags: []
trigger:
    type: pub-sub
    channel: testchannel
    local: false
libraries:
    - testLibrary
includes:
    - /functions/GoodFunc_pubsub.go
execution:
    timeout: 10s
    memory: 10MB
    call: ping
