id: QmZjBpQzRw8UovKaMoWJ3qvQrHZvErqQuXNyXNusm4XYK3
description: This Function should work
tags: []
source: libraries/testLibrary
trigger:
    type: https
    method: GET
    paths:
        - /poopstick
domains:
    - GoodDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
