id: Qmbeyw6GNk8ccAkzHiBeS9J4nKuaFY2kLDh9e4i8AGA4oa
description: Description-dreamland
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GoodDomain
includes: []
execution:
    timeout: 22s
    memory: 2MB
    call: main
