id: QmcDraVuJndSpb1WMrYNWWjrXeBQ5dRwTEN1VrkyxgYR1T
description: ""
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /hello
domains:
    - taf
includes:
    - /functions/pinger_clone.go
execution:
    timeout: 10s
    memory: 10MB
    call: quplo
