id: QmZdVReKoN3kmCoqCK61FAfNszFwoW8JHhDh6sN3xzEkie
description: Description
tags:
    - tag
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GoodDomain
includes: []
execution:
    timeout: 22s
    memory: 2MB
    call: main
