id: QmVFx7wSgUAU4Nnj4YpRQjujf6kWUi2gn2Hp16kBu4KfiA
description: Description-dreamland
tags:
    - tag
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GoodDomain
includes: []
execution:
    timeout: 22s
    memory: 2MB
    call: main
