id: Qmdia4zPGfrr7qW5QfWfMcCtDPsFrjmeMk1bV5dGafVNLe
description: Description
tags:
    - tag
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GoodDomain
includes: []
execution:
    timeout: 22s
    memory: 2MB
    call: main
