id: QmXybsgxX726s8t1uDbcJax5EL6m8LKkRFSJmcriQrVtKw
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /senddata
domains:
    - GoodDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
